"""add contact_holiday unique constraint

Revision ID: 5ac138478a05
Revises: a1b2c3d4e5f6
Create Date: 2026-09-16 14:58:13.130365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ac138478a05'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_contact_holiday', 't_contact_holiday', ['contact_id', 'holiday_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_contact_holiday', 't_contact_holiday', type_='unique')
    # ### end Alembic commands ###
