"""add t_reminder

Revision ID: be97f2c81c84
Revises: 5ac138478a05
Create Date: 2026-09-16 15:33:40.969898

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be97f2c81c84'
down_revision: Union[str, None] = '5ac138478a05'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_reminder',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('reminder_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('anniversary_id', sa.String(length=32), nullable=True),
    sa.Column('holiday_id', sa.String(length=32), nullable=True),
    sa.Column('event_title', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('remind_time', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('blessing', sa.Text(), nullable=True),
    sa.Column('gifts', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_reminder_reminder_id'), 't_reminder', ['reminder_id'], unique=True)
    op.create_index(op.f('ix_t_reminder_user_id'), 't_reminder', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_t_reminder_user_id'), table_name='t_reminder')
    op.drop_index(op.f('ix_t_reminder_reminder_id'), table_name='t_reminder')
    op.drop_table('t_reminder')
    # ### end Alembic commands ###
