"""create anniversary and holiday tables

Revision ID: ffbc7185d0c3
Revises: 7e6194314a39
Create Date: 2026-09-16 14:41:31.345465

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffbc7185d0c3'
down_revision: Union[str, None] = '7e6194314a39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_anniversary',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('anniversary_id', sa.String(length=32), nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=False),
    sa.Column('title_key', sa.String(length=32), nullable=True),
    sa.Column('month_day', sa.String(length=5), nullable=False),
    sa.Column('repeat_type', sa.String(length=20), nullable=False),
    sa.Column('next_date', sa.Date(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_anniversary_anniversary_id'), 't_anniversary', ['anniversary_id'], unique=True)
    op.create_index(op.f('ix_t_anniversary_contact_id'), 't_anniversary', ['contact_id'], unique=False)
    op.create_index(op.f('ix_t_anniversary_user_id'), 't_anniversary', ['user_id'], unique=False)
    op.create_table('t_anniversary_template',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('title_key', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('default_repeat', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title_key')
    )
    op.create_table('t_contact_holiday',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('contact_id', sa.String(length=32), nullable=False),
    sa.Column('holiday_id', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.String(length=32), nullable=False),
    sa.Column('remind_enabled', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_contact_holiday_contact_id'), 't_contact_holiday', ['contact_id'], unique=False)
    op.create_index(op.f('ix_t_contact_holiday_user_id'), 't_contact_holiday', ['user_id'], unique=False)
    op.create_table('t_system_holiday',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('holiday_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('date_rule', sa.String(length=100), nullable=False),
    sa.Column('applicable_relationships', sa.JSON(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holiday_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_system_holiday')
    op.drop_index(op.f('ix_t_contact_holiday_user_id'), table_name='t_contact_holiday')
    op.drop_index(op.f('ix_t_contact_holiday_contact_id'), table_name='t_contact_holiday')
    op.drop_table('t_contact_holiday')
    op.drop_table('t_anniversary_template')
    op.drop_index(op.f('ix_t_anniversary_user_id'), table_name='t_anniversary')
    op.drop_index(op.f('ix_t_anniversary_contact_id'), table_name='t_anniversary')
    op.drop_index(op.f('ix_t_anniversary_anniversary_id'), table_name='t_anniversary')
    op.drop_table('t_anniversary')
    # ### end Alembic commands ###
